### ISSUE TITLE
i didn't get any reading. 

### ISSUE THREAD

**Issue by AVandThings** [astuder/BMP085-template-library-Energia#1]
It shows temperature as 0.0C and pressure as 2hPa. No change in reading nothing. Please help me !!

**Comment by astuder** [comment]
Please use the 43oh forum for questions.
http://forum.43oh.com/topic/3777-energia-library-bosch-bmp085-template-library/

0-readings typically are caused by wrong wiring of I2C. There also seem to be issues with I2C in newer version of Energia.
